---
- hosts: 127.0.0.1
  vars:
    - ansible_python_interpreter: /usr/bin/python2
  tasks:
    - name: pacman -Syy
      pacman: update_cache=yes
      sudo: yes

    - name: Install vim
      pacman: name=gvim
      sudo: yes
    - name: Setup vimrc
      file: src=~/dotfiles/{{item.path}} dest=~/{{item.dest}} state=link
      with_items:
        - { path: '.vim', dest: '.vim' }
        - { path: '.vimrc', dest: '.vimrc' }
        - { path: '.gvimrc', dest: '.gvimrc' }

    - name: Install emacs
      pacman: name=emacs
      sudo: yes
    - name: Setup emacs.d
      file: src=~/dotfiles/.emacs.d dest=~/.emacs.d state=link

    - name: Install firefox
      pacman: name=firefox,flashplugin
      sudo: yes
    - pacman: name=zathura,zathura-pdf-mupdf
      sudo: yes
    - pacman: name=alsa-utils
      sudo: yes

    - name: Setup .gitconfig
      file: src=~/dotfiles/.gitconfig dest=~/.gitconfig state=link

