---
- hosts: archnote
  vars:
    - ansible_python_interpreter: /usr/bin/python2
  tasks:
    - name: Check whether packer installed
      command: pacman -Qi packer
      register: packer_installed
      ignore_errors: True
    - name: Install dependencies for packer
      pacman: name=jshon,expac,git
      sudo: yes
      when: packer_installed|failed
    - name: Download PKGBUILD
      get_url: dest=/tmp url=https://aur.archlinux.org/packages/pa/packer/PKGBUILD
      when: packer_installed|failed
    - name: Build packer
      command: makepkg -f chdir=/tmp
      when: packer_installed|failed
    - name: Install packer
      shell: pacman -U packer-*.pkg.tar.xz --noconfirm chdir=/tmp
      sudo: yes
      when: packer_installed|failed
